apiVersion: v1
kind: Service
metadata:
  name: fimpy-service
  labels:
    name: fimpy-app
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: fimpy-service
  selector:
    app: fimpy-app