apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fimpy-app
  labels:
    app: fimpy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fimpy-app
  template:
    metadata:
      labels:
        app: fimpy-app
    spec:
      containers:
      - name: fimpy-app
        image: alanoneill/fimpy
        env:
        - name: SLACKTOKEN
          value: ""
        ports:
        - containerPort: 5000
