apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fimpy-app
  labels:
    app: fimpy-app
spec:
  selector:
    matchLabels:
      app: fimpy-app
  template:
    metadata:
      labels:
        app: fimpy-app
    spec:
      containers:
      - name: fimpy-app
        image: alanoneill/fimpy
        env:
        - name: SLACKTOKEN
          value: "xoxp-263593032944-263593033264-285370171619-af047513158f7673de13a587fad919b3"
        ports:
        - containerPort: 5000
