apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fimpy-app
  labels:
    app: fimpy-app
spec:
  selector:
    matchLabels:
      app: fimpy-app
  template:
    metadata:
      labels:
        app: fimpy-app
    spec:
      containers:
      - name: fimpy-app
        image: alanoneill/fimpy
        env:
        - name: SLACKTOKEN
          value: "xoxp-263593032944-263593033264-269519073923-d49237434619d65ecbeb11bd5e44bcd8"
        ports:
        - containerPort: 5000
